"""added content to room model

Revision ID: 0e0128d52e66
Revises: 98d3ebbe4b5d
Create Date: 2026-05-25 23:52:41.404726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0128d52e66'
down_revision: Union[str, Sequence[str], None] = '98d3ebbe4b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('content_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_rooms_content_id'), 'rooms', ['content_id'], unique=False)
    op.create_foreign_key(op.f('fk_rooms_content_id_contents'), 'rooms', 'contents', ['content_id'], ['content_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rooms_content_id_contents'), 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_content_id'), table_name='rooms')
    op.drop_column('rooms', 'content_id')
    # ### end Alembic commands ###
