"""updated room modelto support link upload and video id

Revision ID: 379ca3ac2b09
Revises: 8a2d837e1564
Create Date: 2026-05-30 23:00:18.384147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379ca3ac2b09'
down_revision: Union[str, Sequence[str], None] = '8a2d837e1564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('movie_id', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('movie_link', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'provider')
    op.drop_column('rooms', 'movie_link')
    op.drop_column('rooms', 'movie_id')
    # ### end Alembic commands ###
