"""empty message

Revision ID: 5e81982e104a
Revises: 379ca3ac2b09
Create Date: 2026-07-19 20:11:29.422238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e81982e104a'
down_revision: Union[str, Sequence[str], None] = '379ca3ac2b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Success', 'Failed', 'Refunded', name='status'), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], name=op.f('fk_payments_plan_id_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_amount'), 'payments', ['amount'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_amount'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
