"""add a default field to the plan model

Revision ID: 7acbed8be593
Revises: b57f8a28d498
Create Date: 2026-04-16 19:53:15.647187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acbed8be593'
down_revision: Union[str, Sequence[str], None] = 'b57f8a28d498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_plans_is_default'), 'plans', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_is_default'), table_name='plans')
    op.drop_column('plans', 'is_default')
    # ### end Alembic commands ###
