"""add contents table and and rooms table

Revision ID: 98d3ebbe4b5d
Revises: badd3768580b
Create Date: 2026-05-25 16:41:47.634294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d3ebbe4b5d'
down_revision: Union[str, Sequence[str], None] = 'badd3768580b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('content_type', sa.Enum('VIDEO', 'SHORT', name='contenttype'), nullable=False),
    sa.Column('r2_key', sa.String(length=600), nullable=False),
    sa.Column('url', sa.String(length=2500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2500), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.user_id'], name=op.f('fk_contents_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('content_id', name=op.f('pk_contents'))
    )
    op.create_index(op.f('ix_contents_content_id'), 'contents', ['content_id'], unique=True)
    op.create_index(op.f('ix_contents_r2_key'), 'contents', ['r2_key'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_uploaded_by_id'), 'contents', ['uploaded_by_id'], unique=False)
    op.create_table('rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(), nullable=False),
    sa.Column('room_state', sa.String(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('max_guest', sa.Integer(), nullable=False),
    sa.Column('no_guest', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('playback_position', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], name=op.f('fk_rooms_host_id_users')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_rooms'))
    )
    op.create_index(op.f('ix_rooms_host_id'), 'rooms', ['host_id'], unique=False)
    op.create_index(op.f('ix_rooms_is_active'), 'rooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_rooms_max_guest'), 'rooms', ['max_guest'], unique=False)
    op.create_index(op.f('ix_rooms_no_guest'), 'rooms', ['no_guest'], unique=False)
    op.create_index(op.f('ix_rooms_playback_position'), 'rooms', ['playback_position'], unique=False)
    op.create_index(op.f('ix_rooms_room_code'), 'rooms', ['room_code'], unique=True)
    op.create_index(op.f('ix_rooms_room_id'), 'rooms', ['room_id'], unique=True)
    op.create_index(op.f('ix_rooms_room_state'), 'rooms', ['room_state'], unique=False)
    op.create_table('room_members',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_room_members_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_room_members_user_id_users')),
    sa.PrimaryKeyConstraint('member_id', name=op.f('pk_room_members'))
    )
    op.create_index(op.f('ix_room_members_member_id'), 'room_members', ['member_id'], unique=True)
    op.create_index(op.f('ix_room_members_role'), 'room_members', ['role'], unique=False)
    op.create_index(op.f('ix_room_members_room_id'), 'room_members', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_members_user_id'), 'room_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_members_user_id'), table_name='room_members')
    op.drop_index(op.f('ix_room_members_room_id'), table_name='room_members')
    op.drop_index(op.f('ix_room_members_role'), table_name='room_members')
    op.drop_index(op.f('ix_room_members_member_id'), table_name='room_members')
    op.drop_table('room_members')
    op.drop_index(op.f('ix_rooms_room_state'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_code'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_playback_position'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_no_guest'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_max_guest'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_is_active'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_host_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_contents_uploaded_by_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_r2_key'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_id'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
