"""add a field for storing raw code for easy lookup'


Revision ID: b57f8a28d498
Revises: de26ae9e7ef2
Create Date: 2026-04-16 19:31:18.363595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57f8a28d498'
down_revision: Union[str, Sequence[str], None] = 'de26ae9e7ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('raw_code', sa.String(), nullable=False, server_default="00000"))
    op.create_index(op.f('ix_otp_codes_raw_code'), 'otp_codes', ['raw_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_raw_code'), table_name='otp_codes')
    op.drop_column('otp_codes', 'raw_code')
    # ### end Alembic commands ###
