"""empty message

Revision ID: b5ca97ae1327
Revises: f5e0e13981cf
Create Date: 2026-07-19 23:23:55.085357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ca97ae1327'
down_revision: Union[str, Sequence[str], None] = 'f5e0e13981cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('is_daily', sa.Boolean(), nullable=True))
    op.add_column('plans', sa.Column('is_monthly', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_plans_is_daily'), 'plans', ['is_daily'], unique=False)
    op.create_index(op.f('ix_plans_is_monthly'), 'plans', ['is_monthly'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_is_monthly'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_daily'), table_name='plans')
    op.drop_column('plans', 'is_monthly')
    op.drop_column('plans', 'is_daily')
    # ### end Alembic commands ###
