"""added content to room model

Revision ID: ca993bd9d673
Revises: 0e0128d52e66
Create Date: 2026-05-25 23:53:41.669351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca993bd9d673'
down_revision: Union[str, Sequence[str], None] = '0e0128d52e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'content_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'content_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
