"""add session key field for membership model

Revision ID: dbe028f0b91b
Revises: 047567844e9f
Create Date: 2026-05-27 00:43:49.474985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe028f0b91b'
down_revision: Union[str, Sequence[str], None] = '047567844e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('session_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_room_members_session_key'), 'room_members', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_members_session_key'), table_name='room_members')
    op.drop_column('room_members', 'session_key')
    # ### end Alembic commands ###
