""" initail migrations

Revision ID: de26ae9e7ef2
Revises: 
Create Date: 2026-04-16 11:38:31.770025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de26ae9e7ef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('storage_limit_mb', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_index(op.f('ix_plans_plan_id'), 'plans', ['plan_id'], unique=True)
    op.create_index(op.f('ix_plans_price'), 'plans', ['price'], unique=False)
    op.create_index(op.f('ix_plans_storage_limit_mb'), 'plans', ['storage_limit_mb'], unique=False)
    op.create_index(op.f('ix_plans_updated_at'), 'plans', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('hash_code', sa.LargeBinary(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_otp_codes_user_id_users')),
    sa.PrimaryKeyConstraint('otp_id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_hash_code'), 'otp_codes', ['hash_code'], unique=False)
    op.create_index(op.f('ix_otp_codes_is_active'), 'otp_codes', ['is_active'], unique=False)
    op.create_index(op.f('ix_otp_codes_is_used'), 'otp_codes', ['is_used'], unique=False)
    op.create_index(op.f('ix_otp_codes_otp_id'), 'otp_codes', ['otp_id'], unique=True)
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], name=op.f('fk_subscriptions_plan_id_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_otp_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_is_used'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_is_active'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_hash_code'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_updated_at'), table_name='plans')
    op.drop_index(op.f('ix_plans_storage_limit_mb'), table_name='plans')
    op.drop_index(op.f('ix_plans_price'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
