"""new model chats

Revision ID: f679388f38a1
Revises: dbe028f0b91b
Create Date: 2026-05-27 02:37:26.356670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f679388f38a1'
down_revision: Union[str, Sequence[str], None] = 'dbe028f0b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('session_key', sa.String(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('fk_chats_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_chats_user_id_users')),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_chats'))
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
